# -*- coding: utf-8 -*-
"""myAssignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNmgDig6cCfJYkUnhLHRRuKTvC-G0PhD

Assignment-2
"""

#Assignment-2
#Date:29/06/2021
#Amal V.V
#amalvv2000cit@gmail.com



"""# **FOOTBALL WINNER PREDICTOR (LOTTERY TYPE PROGRAM)**"""

n=int(input("Enter Number of Team qualified for Euro Cup :"))
print("\n")
Teams=[input("Enter the name of teams : ") for i in range(n)]

print("\n")
print("\n")

print("THE TEAMS IN THE TOURNAMENT ARE : ",Teams)
import random
x=random.randint(0,n-1)

print('\n')
print("The WINNER OF EURO 2021 IS............. ",Teams[x])



